# Generated by Django 2.1.2 on 2019-07-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Githubevent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_id', models.CharField(blank=True, max_length=50, null=True)),
                ('issue_title', models.CharField(blank=True, max_length=255, null=True)),
                ('action', models.CharField(blank=True, max_length=50, null=True)),
                ('repository', models.CharField(blank=True, max_length=255, null=True)),
                ('repo_owner', models.CharField(blank=True, max_length=50, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'githubevent',
                'managed': False,
            },
        ),
    ]
